version: "3.8"

services:
  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    ports:
      - "8091:80"
    deploy:
      resources:
        limits:
          memory: 512M  # Limite stricte à 512 Mo de RAM
          cpus: "0.5"   # Limite le CPU à 50 %
        reservations:
          memory: 256M  # Réserve un minimum de 256 Mo
          cpus: "0.25"  # Réserve un minimum de 25 %

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpass
    deploy:
      resources:
        limits:
          memory: 1024M  # Limite stricte à 1 Go de RAM
          cpus: "0.7"    # Limite le CPU à 70 %
        reservations:
          memory: 512M   # Réserve un minimum de 512 Mo
          cpus: "0.5"    # Réserve un minimum de 50 %
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:


